WeatherCheck/Models/ErrorViewModel.cs
using System;

namespace WeatherCheck.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WeatherCheck/Models/Weather.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WeatherCheck.Models
{
	public class Weather
	{
		[Key]
		public int Id { get; set; }
		[DataType(DataType.Date)]
		[Display(Name = "Дата")]
		public DateTime Date { get; set; }
		[DataType(DataType.Time)]
		[Display(Name = "Время")]
		public DateTime Time { get; set; }
		[Display(Name = "Т")]
		public float? Temperature { get; set; }
		[Display(Name = "Отн.влажность, %")]
		[Range(0, 100)]
		public float? RelativeHumidity { get; set; }
		[Display(Name = "Td")]
		public float? DewPoint { get; set; }
		[Display(Name = "Атм.давление, мм рт.ст.")]
		public short? AtmosphericPressure { get; set; }

		[StringLength(50)]
		[Display(Name = "Направление ветра")]
		public string WindDirection { get; set; }
		[Display(Name = "Скорость ветра")]
		public byte? WindSpeed { get; set; }

		[Display(Name = "Облачность")]
		[Range(0, 100)]
		public byte? Cloudiness { get; set; }
		[Display(Name = "H")]
		public short? CloudCeiling { get; set; }

		[StringLength(50)]
		[Display(Name = "VV")]
		public string HorizontalVisibility { get; set; }
		[Display(Name = "Погодные явления")]
		[StringLength(500)]
		public string WeatherEvents { get; set; }

	}

	public enum Month
	{
		Choose = 0,
		January,
		February,
		March,
		April,
		May,
		June,
		July,
		August,
		September,
		October,
		November,
		December
	}
}

WeatherCheck/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WeatherCheck.Models;

namespace WeatherCheck.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger; 

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WeatherCheck/Controllers/WeatherController.cs
using System;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WeatherCheck.Data;
using WeatherCheck.Models;
using System.Data;
using WeatherCheck.Help;
using Microsoft.Data.SqlClient;

namespace WeatherCheck.Controllers
{
    public class WeatherController : Controller
    {
        private readonly WeatherCheckContext _context;

        public WeatherController(WeatherCheckContext context)
        {
            _context = context;
        }

        public PaginatedList<Weather> WeatherPaginatedList { get; set; }


        public async Task<IActionResult> Index(int? pageNumber, string searchMonth, string searchYear)
        {
            int pageSize = 10;

            IQueryable<Weather> weatherLog =
                _context.Weather.OrderByDescending(x => x.Date);

            if (!string.IsNullOrEmpty(searchMonth) && int.TryParse(searchMonth, out var month))
            {
                weatherLog = weatherLog.Where(x => x.Date.Month == month);
            }
            if (!string.IsNullOrEmpty(searchYear) && int.TryParse(searchYear, out var year))
            {
                weatherLog = weatherLog.Where(x => x.Date.Year == year);
            }
            WeatherPaginatedList = await PaginatedList<Weather>.CreateAsync(weatherLog.AsNoTracking(), pageNumber ?? 1, pageSize);

            return View(WeatherPaginatedList);
        }

        [HttpGet]
        public IActionResult Import()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Import(List<IFormFile> files)
        {
            if (files.Count <= 0)
                return View();

            DataTable dt = new DataTable();

            foreach (var file in files)
            {
                string FileName = Path.GetExtension(file.FileName);
                if (FileName != ".xls" && FileName != ".xlsx")
                {
                    continue;
                }
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), file.FileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {

                    await file.CopyToAsync(stream);
                    stream.Position = 0;
                    try
                    {
                        if (FileName == ".xls")
                        {
                            HSSFWorkbook workbook = new HSSFWorkbook(stream);
                            dt = ExcelService.GetDataTableFromExcel(dt, workbook);
                        }
                        else
                        {
                            XSSFWorkbook workbook = new XSSFWorkbook(stream);
                            dt = ExcelService.GetDataTableFromExcel(dt, workbook);
                        }

                    }
                    catch (Exception e)
                    {
                        ViewData["ErrorImport"] = "Ошибка при импортировании данных: \n" + e.Message;
                        continue;
                    }
                }
            }

            try
            {
                string consString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=WeatherCheckContext-83b70fb5-d984-477b-a6b7-8f823f1039bf;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";

                using (SqlConnection con = new SqlConnection(consString))
                {
                    using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(con))
                    {
                        //Set the database table name
                        sqlBulkCopy.DestinationTableName = "dbo.Weather";
                        //[OPTIONAL]: Map the DataTable columns with that of the database table
                        sqlBulkCopy.ColumnMappings.Add("Date", "Date");
                        sqlBulkCopy.ColumnMappings.Add("Time", "Time");
                        sqlBulkCopy.ColumnMappings.Add("Temperature", "Temperature");
                        sqlBulkCopy.ColumnMappings.Add("RelativeHumidity", "RelativeHumidity");
                        sqlBulkCopy.ColumnMappings.Add("DewPoint", "DewPoint");
                        sqlBulkCopy.ColumnMappings.Add("AtmosphericPressure", "AtmosphericPressure");
                        sqlBulkCopy.ColumnMappings.Add("WindDirection", "WindDirection");
                        sqlBulkCopy.ColumnMappings.Add("WindSpeed", "WindSpeed");
                        sqlBulkCopy.ColumnMappings.Add("Cloudiness", "Cloudiness");
                        sqlBulkCopy.ColumnMappings.Add("CloudCeiling", "CloudCeiling");
                        sqlBulkCopy.ColumnMappings.Add("HorizontalVisibility", "HorizontalVisibility");
                        sqlBulkCopy.ColumnMappings.Add("WeatherEvents", "WeatherEvents");
                        con.Open();
                        sqlBulkCopy.WriteToServer(dt);
                        con.Close();
                    }
                }
                ViewData["SQLResult"] = "Данные успешно добавлены. Количество строк: " + dt.Rows.Count;
            }
            catch(Exception e)
            {
                ViewData["SQLResult"] = "Ошибка при сохранении в БД: \n" + e.Message;         
            }

            return View();

        }
    }    
  
}

WeatherCheck/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Weather Archives";
}

<div class="text-center">
    <h2 class="display-4">Добро пожаловать</h2>
    <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Import">Загрузка</a>
    <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Index">Просмотр</a>

</div>

WeatherCheck/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Weather Control</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Weather Archives</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!--
    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
        </ul>
    </div
                    -->
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Weather Control</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WeatherCheck/Views/Weather/Import.cshtml
@{
    ViewData["Title"] = "Weather Upload";
}
<h3>Загрузка архивов по погоде в Москве</h3>
<div class="m-2">
    <p>Выберите один или несколько файлов</p>
    <div>
        <form method="post" asp-controller="Weather" asp-action="Import" enctype="multipart/form-data">
            <input type="file" name="files" multiple />
            <button type="submit">Загрузить</button>
            <div class="form-group">
                <span>@ViewData["ErrorImport"]</span>
            </div>
            <div class="form-group">
                <span>@ViewData["SQLResult"]</span>
            </div>
        </form>
    </div>
</div>

WeatherCheck/Views/Weather/Index.cshtml
@model PaginatedList<WeatherCheck.Models.Weather>

@{
    ViewData["Title"] = "Weather View";
}

<h3>Архив данных по погоде в Москве</h3>

<form asp-action="Index" method="get">
    <div class="form-row">
        <p class="m-2">Фильтр по номеру месяца и года:</p>
        <div class="form-actions no-color m-2">
            <p>
                <input type="text" name="searchMonth" placeholder="Месяц" />
            </p>
        </div>
        <div class="form-actions no-color m-2">
            <p>
                <input type="text" name="searchYear" placeholder="Год" />
            </p>
        </div>
        <div class="form-actions no-color m-2" style="margin-bottom:10px">
            <button type="submit" class="btn btn-primary btn-sm">Применить</button>
            <a asp-action="Index">Очистить</a>
        </div>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Temperature)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().RelativeHumidity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().DewPoint)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().AtmosphericPressure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().WindDirection)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().WindSpeed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Cloudiness)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().CloudCeiling)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().HorizontalVisibility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().WeatherEvents)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Temperature)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RelativeHumidity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DewPoint)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AtmosphericPressure)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WindDirection)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WindSpeed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cloudiness)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CloudCeiling)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HorizontalVisibility)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WeatherEvents)
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>